NODES = {
  'control-plane' => {
    ip: '192.168.10.10',
    ports: {
      'ssh' => { guest: 22, host: 2221 },
      'k8s-api' => { guest: 6443, host: 6443 }
    },
    cpus: 2,
    memory: 2048,
    disk_size: "64GB",
    synced_folder: false
  },
  'worker-1' => {
    ip: '192.168.10.11',
    ports: {
      'ssh' => { guest: 22, host: 2222 }
    },
    cpus: 2,
    memory: 2048,
    disk_size: "64GB",
    synced_folder: false
  },
  'worker-2' => {
    ip: '192.168.10.12',
    ports: {
      'ssh' => { guest: 22, host: 2223 } 
    },
    cpus: 2,
    memory: 2048,
    disk_size: "64GB",
    synced_folder: false
  }
}

Vagrant.configure("2") do |config|
  # https://portal.cloud.hashicorp.com/vagrant/discover/bento/ubuntu-24.04
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202508.03.0"

  NODES.each do |node_name, node_config|
    config.vm.define node_name do |node|
      node.vm.hostname = node_name

      # Configure the network
      node.vm.network "private_network", ip: node_config[:ip], auto_config: true, virtualbox__intnet: true
      node_config[:ports].each do |id, port_config|
        node.vm.network "forwarded_port", id: id, guest: port_config[:guest], host: port_config[:host]
      end

      # Configure the hardware
      node.vm.provider "virtualbox" do |vb|
        vb.name = node_name
        vb.cpus = node_config[:cpus]
        vb.memory = node_config[:memory]
      end

      # Configure a primary disk
      node.vm.disk :disk, size: node_config[:disk_size], primary: true

      # Configure the default /vagrant shared folder
      node.vm.synced_folder ".", "/vagrant", disabled: !node_config[:synced_folder]

      # Configure the Kubernetes cluster
      node.vm.provision "k8s_setup", type: "shell", path: "k8s-setup.sh", env: {
        "NODE_IPS" => NODES.map { |name, conf| "#{conf[:ip]} #{name}" }.join(',')
      }
    end
  end
end
